- name: variables
  hosts: web
  vars: 
    script: script
    variable: variables
  tasks:
    - name: This is used for variables
      ansible.builtin.debug:
        msg: "This is the yaml {{script}} for the {{variable}}."